name: CI/CD pipeline with slack
on:
  push:
    branches : ["main","master"]
jobs:
    build:
        runs-on : windows-latest
    steps:
        - uses : actions/checkout@v4
        - uses : actions/setup-java@v4
          with:
            distribution :'tumerin'
            java-version :"11"

        - name: build using maven
          run : mvn clean install
         